apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: authentik-postgres-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./authentik-postgres-secret.yaml
