# Infrastructure Layer - Operators and Core Services
# Sync Wave: 0 (deploys first)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/berleon/enty-ai-internal-infrastructure.git
    targetRevision: main
    path: argocd/infrastructure/
    directory:
      recurse: true
      exclude: 'app-of-apps.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
