apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: forgejo-oauth-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./forgejo-oauth-authentik-secret.yaml
