# CronJob for daily Forgejo database backups to S3
# S3 credentials are provided by s3-backup-credentials-secret.yaml (encrypted with SOPS)
apiVersion: batch/v1
kind: CronJob
metadata:
  name: forgejo-backup-s3
  namespace: forgejo
spec:
  schedule: "0 3 * * *"  # Daily at 3 AM UTC
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: forgejo-backup
          containers:
            - name: backup
              image: amazon/aws-cli:latest
              command:
                - /bin/sh
                - -c
                - |
                  set -e
                  TIMESTAMP=$(date +%Y%m%d-%H%M%S)
                  BACKUP_FILE="/tmp/forgejo-backup-${TIMESTAMP}.zip"

                  # Install kubectl
                  echo "Installing kubectl..."
                  curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
                  chmod +x kubectl
                  mv kubectl /usr/local/bin/

                  # Get Forgejo pod
                  echo "Finding Forgejo pod..."
                  POD=$(kubectl get pod -n forgejo -l app.kubernetes.io/name=forgejo -o jsonpath='{.items[0].metadata.name}')
                  echo "Using pod: $POD"

                  # Ensure repository directory exists (for fresh installations)
                  echo "Checking repository directory..."
                  kubectl exec -n forgejo $POD -- mkdir -p /data/git/gitea-repositories

                  # Create backup using Forgejo's built-in dump command
                  echo "Creating backup dump..."
                  kubectl exec -n forgejo $POD -- forgejo dump -f - > "$BACKUP_FILE"

                  echo "Backup created: $(ls -lh $BACKUP_FILE)"

                  # Upload to S3
                  echo "Uploading to S3..."
                  aws s3 cp "$BACKUP_FILE" "s3://${S3_BUCKET}/forgejo-backup-${TIMESTAMP}.zip" --endpoint-url="${S3_ENDPOINT}"

                  echo "Backup completed successfully: forgejo-backup-${TIMESTAMP}.zip"

                  # Cleanup
                  rm -f "$BACKUP_FILE"
              env:
                - name: S3_BUCKET
                  valueFrom:
                    secretKeyRef:
                      name: s3-backup-credentials
                      key: bucket
                - name: S3_ENDPOINT
                  valueFrom:
                    secretKeyRef:
                      name: s3-backup-credentials
                      key: endpoint
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: s3-backup-credentials
                      key: access-key
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: s3-backup-credentials
                      key: secret-key
                - name: AWS_DEFAULT_REGION
                  value: "us-east-1"
          restartPolicy: OnFailure
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3

---
# ServiceAccount for the backup job
apiVersion: v1
kind: ServiceAccount
metadata:
  name: forgejo-backup
  namespace: forgejo

---
# Role for the backup job (minimal permissions)
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: forgejo-backup
  namespace: forgejo
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec"]
    verbs: ["get", "list", "create"]

---
# RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: forgejo-backup
  namespace: forgejo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: forgejo-backup
subjects:
  - kind: ServiceAccount
    name: forgejo-backup
    namespace: forgejo
