apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: postgres-credentials-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./postgres-credentials.yaml
