apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: postgresql-shared-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./postgresql-shared-secret.yaml
