# Single source of truth for KSOPS configuration on argocd-repo-server
# This patch is used by both GitOps (argocd-config) and initial setup (install)
#
# Enables SOPS/KSOPS for encrypted secrets management:
# - Installs KSOPS and Kustomize binaries via init container
# - Mounts age key for automatic decryption
# - Sets SOPS_AGE_KEY_FILE environment variable
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
  namespace: argocd
spec:
  template:
    spec:
      # Volumes for KSOPS and age key
      volumes:
        - name: custom-tools
          emptyDir: {}
        - name: sops-age
          secret:
            secretName: sops-age
            # 292 = 0o444 (world readable) - needed because container runs as argocd user, not root
            defaultMode: 292

      # Init container to install KSOPS
      # Note: viaductoss/ksops is a scratch image without shell, so we use Alpine + wget
      # Detects architecture automatically (amd64 or arm64)
      initContainers:
        - name: install-ksops
          image: alpine:3.19
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -e
              echo "Installing KSOPS and Kustomize..."
              ARCH=$(uname -m)
              case $ARCH in
                x86_64) KSOPS_ARCH="x86_64"; KUST_ARCH="amd64" ;;
                aarch64) KSOPS_ARCH="arm64"; KUST_ARCH="arm64" ;;
                *) echo "Unsupported architecture: $ARCH"; exit 1 ;;
              esac
              echo "Detected architecture: $ARCH (KSOPS: $KSOPS_ARCH, Kustomize: $KUST_ARCH)"
              wget -qO- "https://github.com/viaduct-ai/kustomize-sops/releases/download/v4.4.0/ksops_4.4.0_Linux_${KSOPS_ARCH}.tar.gz" | tar xz -C /custom-tools
              wget -qO- "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv5.4.1/kustomize_v5.4.1_linux_${KUST_ARCH}.tar.gz" | tar xz -C /custom-tools
              chmod +x /custom-tools/ksops /custom-tools/kustomize
              echo "Done."
          volumeMounts:
            - mountPath: /custom-tools
              name: custom-tools

      containers:
        - name: argocd-repo-server
          # Environment variables for SOPS
          env:
            - name: SOPS_AGE_KEY_FILE
              value: /.config/sops/age/keys.txt

          # Volume mounts for KSOPS and age key
          volumeMounts:
            # Override default kustomize with KSOPS version
            - mountPath: /usr/local/bin/kustomize
              name: custom-tools
              subPath: kustomize
            - mountPath: /usr/local/bin/ksops
              name: custom-tools
              subPath: ksops
            # Mount age key for SOPS
            - mountPath: /.config/sops/age
              name: sops-age
