# Root App of Apps - Layered GitOps Structure
#
# This deploys applications in 3 layers with explicit ordering:
#   1. Infrastructure (wave 0) - Operators (Tailscale, PostgreSQL, Argo CD config)
#   2. Platform (wave 1) - Shared services (PostgreSQL cluster, backups)
#   3. Apps (wave 2) - User applications (Forgejo, Authentik)
#
# Workflow:
#   1. Create new Application manifest in appropriate layer directory
#   2. Commit to git
#   3. Argo CD auto-discovers and deploys (within ~3 minutes)
#
# Structure:
#   argocd/infrastructure/  - Core operators and system config
#   argocd/platform/        - Shared platform services
#   argocd/apps/            - User-facing applications

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    # Layer 1: Infrastructure (sync wave 0)
    - repoURL: https://github.com/berleon/enty-ai-internal-infrastructure.git
      targetRevision: main
      path: argocd/infrastructure/
      directory:
        recurse: false
        include: 'app-of-apps.yaml'

    # Layer 2: Platform (sync wave 1)
    - repoURL: https://github.com/berleon/enty-ai-internal-infrastructure.git
      targetRevision: main
      path: argocd/platform/
      directory:
        recurse: false
        include: 'app-of-apps.yaml'

    # Layer 3: Apps (sync wave 2)
    - repoURL: https://github.com/berleon/enty-ai-internal-infrastructure.git
      targetRevision: main
      path: argocd/apps/
      directory:
        recurse: false
        include: 'app-of-apps.yaml'

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
