# App of Apps Pattern for Argo CD
# This application automatically deploys all Application manifests in argocd/applications/ directory
#
# Workflow:
# 1. Create new Application manifest in argocd/applications/
# 2. Commit to git
# 3. Argo CD auto-discovers and deploys (within ~3 minutes)
#
# This enables fully automated GitOps - just commit an Application and it deploys!

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/berleon/enty-ai-internal-infrastructure.git
    targetRevision: main
    path: argocd/applications/
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
