apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: s3-backup-credentials-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./s3-backup-credentials-secret.yaml
