# CronJob for daily Forgejo database backups to S3
# S3 credentials are provided by s3-backup-credentials-secret.yaml (encrypted with SOPS)
apiVersion: batch/v1
kind: CronJob
metadata:
  name: forgejo-backup-s3
  namespace: forgejo
spec:
  schedule: "0 3 * * *"  # Daily at 3 AM UTC
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: forgejo-backup
          containers:
            - name: backup
              image: bitnami/kubectl:latest
              command:
                - /bin/sh
                - -c
                - |
                  # Get Forgejo pod
                  POD=$(kubectl get pod -n forgejo -l app.kubernetes.io/name=forgejo -o jsonpath='{.items[0].metadata.name}')

                  # Create backup
                  kubectl exec -n forgejo $POD -- sh -c 'sqlite3 /data/gitea.db .dump' > /tmp/backup.sql

                  # Upload to S3
                  apt-get update && apt-get install -y aws-cli
                  aws s3 cp /tmp/backup.sql s3://$S3_BUCKET/forgejo-backup-$(date +%Y%m%d-%H%M%S).sql

                  # Cleanup
                  rm -f /tmp/backup.sql
              env:
                - name: S3_BUCKET
                  valueFrom:
                    secretKeyRef:
                      name: s3-backup-credentials
                      key: bucket
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: s3-backup-credentials
                      key: access-key
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: s3-backup-credentials
                      key: secret-key
                - name: AWS_DEFAULT_REGION
                  value: "us-east-1"
          restartPolicy: OnFailure
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
