apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: cloudnative-pg
    repoURL: https://cloudnative-pg.github.io/charts
    targetRevision: 0.27.0
    helm:
      releaseName: cloudnative-pg
      values: |
        # Minimal resource footprint for 4GB ARM64 node
        resources:
          requests:
            cpu: 25m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi

        # Watch entire cluster for all PostgreSQL instances
        config:
          clusterWide: true
          create: true

        # Security context (ARM64 compatible)
        containerSecurityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 10001
          runAsGroup: 10001
          seccompProfile:
            type: RuntimeDefault

        podSecurityContext:
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault

        # Skip CRDs - will install separately to avoid annotation size limits
        crds:
          create: false

        # RBAC
        rbac:
          create: true

        # ServiceAccount
        serviceAccount:
          create: true

  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true  # Handle large CRDs
      - Replace=true  # Allow larger annotations
