apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: forgejo-oauth-secret
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/berleon/enty-ai-internal-infrastructure.git
    targetRevision: main
    path: argocd/resources/forgejo-oauth-secret
  destination:
    server: https://kubernetes.default.svc
    namespace: forgejo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
