apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: github-secrets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/berleon/enty-ai-internal-infrastructure.git
    targetRevision: main
    path: argocd/resources/github-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
