apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql-shared
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: postgresql
    repoURL: oci://registry-1.docker.io/bitnamicharts
    targetRevision: 18.2.0
    helm:
      releaseName: postgresql-shared
      values: |
        # Global settings
        global:
          # Use ARM64-compatible image
          imageRegistry: docker.io
          postgresql:
            auth:
              # Reference existing secret for passwords
              existingSecret: postgresql-shared-passwords
              secretKeys:
                adminPasswordKey: postgres-password

        # Image configuration (ARM64 compatible)
        image:
          registry: docker.io
          repository: bitnami/postgresql
          tag: 17.2.0-debian-12-r9
          pullPolicy: IfNotPresent

        # Authentication - uses secret created above
        auth:
          enablePostgresUser: true
          existingSecret: postgresql-shared-passwords
          secretKeys:
            adminPasswordKey: postgres-password

          # Primary database for Authentik (others created via initdb)
          database: "authentik"
          username: "authentik"

        # Primary PostgreSQL configuration
        primary:
          # AGGRESSIVE resource limits for 4GB node
          # PostgreSQL will use 256-512Mi RAM
          resources:
            requests:
              cpu: 50m          # Minimal CPU request
              memory: 256Mi     # Start with 256Mi
            limits:
              cpu: 500m         # Max 0.5 CPU core
              memory: 512Mi     # Hard limit at 512Mi

          # Persistence configuration
          persistence:
            enabled: true
            size: 20Gi
            storageClass: hcloud-volumes
            accessModes:
              - ReadWriteOnce

          # PostgreSQL tuning for LOW MEMORY (512Mi max)
          # Based on https://pgtune.leopard.in.ua for 512Mi RAM
          extendedConfiguration: |
            # Memory settings optimized for 512Mi limit
            shared_buffers = 128MB              # 25% of memory
            effective_cache_size = 384MB        # 75% of memory
            maintenance_work_mem = 32MB         # Conservative
            work_mem = 2MB                      # Low per-connection memory

            # Connection settings
            max_connections = 100               # Reasonable for shared DB

            # WAL settings (minimal for single node)
            wal_buffers = 4MB
            min_wal_size = 512MB
            max_wal_size = 2GB

            # Checkpoint settings
            checkpoint_completion_target = 0.9

            # Query planner
            random_page_cost = 1.1              # SSD-optimized
            effective_io_concurrency = 200      # SSD-optimized

            # Logging (minimal for low overhead)
            log_connections = off
            log_disconnections = off
            log_hostname = off
            log_line_prefix = '%t [%p]: [%l-1] user=%u,db=%d,app=%a,client=%h '

            # Autovacuum (conservative for low memory)
            autovacuum_max_workers = 2
            autovacuum_naptime = 30s

          # Init script to create multiple databases for different services
          initdb:
            scripts:
              # Create additional databases and users
              01-create-databases.sh: |
                #!/bin/bash
                set -e

                echo "Creating additional databases and users..."

                # Get passwords from environment (injected from secret)
                AUTHENTIK_PASSWORD="${AUTHENTIK_PASSWORD}"
                FORGEJO_PASSWORD="${FORGEJO_PASSWORD}"
                PAPERLESS_PASSWORD="${PAPERLESS_PASSWORD}"

                # Create Forgejo database and user
                psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
                  CREATE DATABASE forgejo;
                  CREATE USER forgejo WITH PASSWORD '$FORGEJO_PASSWORD';
                  GRANT ALL PRIVILEGES ON DATABASE forgejo TO forgejo;
                  ALTER DATABASE forgejo OWNER TO forgejo;
                  \c forgejo
                  GRANT ALL ON SCHEMA public TO forgejo;
                EOSQL

                # Create Paperless database and user
                psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
                  CREATE DATABASE paperless;
                  CREATE USER paperless WITH PASSWORD '$PAPERLESS_PASSWORD';
                  GRANT ALL PRIVILEGES ON DATABASE paperless TO paperless;
                  ALTER DATABASE paperless OWNER TO paperless;
                  \c paperless
                  GRANT ALL ON SCHEMA public TO paperless;
                EOSQL

                # Set Authentik user password (database already exists from auth.database)
                psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
                  ALTER USER authentik WITH PASSWORD '$AUTHENTIK_PASSWORD';
                  \c authentik
                  GRANT ALL ON SCHEMA public TO authentik;
                EOSQL

                echo "Databases created successfully:"
                psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" -c "\l"

          # Inject passwords into initdb script via extraEnvVars
          extraEnvVars:
            - name: AUTHENTIK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-shared-passwords
                  key: authentik-password
            - name: FORGEJO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-shared-passwords
                  key: forgejo-password
            - name: PAPERLESS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-shared-passwords
                  key: paperless-password

          # Security context
          containerSecurityContext:
            enabled: true
            readOnlyRootFilesystem: false  # PostgreSQL needs writable filesystem
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1001
            capabilities:
              drop:
                - ALL

          # Pod security context
          podSecurityContext:
            enabled: true
            fsGroup: 1001

        # Metrics (disabled to save resources)
        metrics:
          enabled: false

        # Network policy (disabled for simplicity)
        networkPolicy:
          enabled: false

        # Service configuration
        service:
          type: ClusterIP
          ports:
            postgresql: 5432

        # Volume permissions (ARM64 compatible)
        volumePermissions:
          enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: database

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

  # Health checks
  ignoreDifferences:
    - group: ""
      kind: Secret
      jsonPointers:
        - /data
