apiVersion: v1
kind: Secret
metadata:
    name: s3-backup-credentials
    namespace: forgejo
type: Opaque
stringData:
    access-key: ENC[AES256_GCM,data:dHkeOavUdLlH+o7FEBXjlPhfy34Sbg5hdw==,iv:uybo+dD7Wk08ViDTif6K225d0BvxOTzE8x3M04BaEN0=,tag:/qsZkf5lnIuNRCrYqLghLg==,type:str]
    secret-key: ENC[AES256_GCM,data:N33WbnEBT6RgyfhZ63QjV1/RN0lcLoXb4N9mUuFXpA==,iv:yHuVbyhP8jVACvs3RG1KTPI4SgZhu4cmxMM5ppMzUvM=,tag:65hH/fzIL/nvQB3h457cwg==,type:str]
    bucket: ENC[AES256_GCM,data:ZKnorduwOxM1ceHN+D1biFE6Uy26GE/TsMrUX0qV+w==,iv:he+nFggYnLG6Dbc2WoOvk0fVxCaxRPYpCKrHVyadoSE=,tag:2aJOGy4y4yL238wbm4uAXQ==,type:str]
    endpoint: ENC[AES256_GCM,data:l3Qu1VkyVMcJ7hbAm3Dpw1zhNDq6XDaPdzHRDhqJqb/lm5quW36uhV8=,iv:qLnX70yhWm9s3uj/OulvCxdS+fxarcWl/eiEEmVy3Iw=,tag:8RgqMLAorkMucMVJcwniOA==,type:str]
sops:
    age:
        - recipient: age19lq4dtrxd5qdwkr63gpy2qfwnttu3nxlrp9rxmu659nkt4d8ld7skwj6x9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhbDh5V1JrZkJJOWxTeCtx
            dW9FTHc0VjlrWU5UUnVGaXdCeml1TEk0UUVFCmpQL200dnZwTTlmTmJFWkNXVWtU
            dW5udEtobXFaeXRVblhnVjNzWDBRQkUKLS0tIDFTVlRrSmJXbVZmc3FDOEtIRnp1
            bXY0U0gwWDQ3eVB5Z3NKZjVNZXJZSm8K+DtiU6WmvswSbv2RT4pfmzwWaNmht7J5
            0lH2jA03Mrz3e7WDrIAmVCdst5qfQi5bGL05RbmXY6CHnRuUx6k6pA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-16T15:50:05Z"
    mac: ENC[AES256_GCM,data:t2YdzfIyGOfEcEkAz8uo5RmV06gSZnGD6tlCa6SkgqVBXYzyajzI2t5Cph0aSm53PmNumazGCYQNONEeaPuG+SNuLdAXzzOpQbCDfq02Gugwl+h3dslXQ+PhN9dBBj0sn2g5r+NmSGE2sEQgnUkafu1LWRk078sh8MiXAVvpYiU=,iv:7GckGl2qvrHP8cmsYlqccoWsgtoZ3deXRmaaZ+PND0A=,tag:33QHkLOngpHNmMYt2RoOCQ==,type:str]
    pgp:
        - created_at: "2026-01-16T15:46:00Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxdOhYsagpprARAAo/z/MsXFdL1cVBGODcw1ZqUehjLtIf01JfdpSTpLj1Y3
            NgQhxwsEFk5dcWQZFUaDZZ5X1BvdmHzt+hDkVqJB0ta9SSYKWSMK4R4WDg35UWXk
            L6KkwrRbTvnlOEwM6BzO2plwAnKUZwjwl9W+wZH50rcgfSbRaiHSa3ecqve9NCif
            ITwTjqOVRMKoF0hkJI3WZqaE5VEK/fpl5EuSoen/M8aNNM4qRsqoFUfpZ9B/5PnM
            i1yMCTbhEJbLC3jh8XqBFWTQ+3gMbWAm1L5hT8Hdony627ZtR8hctKJ3RRK8g0JK
            HfkhTGU1S7f5liphm3HHh4DG6nyY6oZMtipgQhtyfRQTZsBbA0VMiElYyH6DCzH4
            dtY0fdyltB+mrlWjlKWdrpsyjd92ppY1yAuWUPNH0Vq0lD4zpj9bHc3x43wcg14G
            DP6XricQ5t0VrQJO8fkk+AE6yGCYcRKBwOD320IsIeCYIWT/Tk6cvShXBCPtNMn3
            co0zmSk3TbWgKXe+1Tez88kT2VMtmFC9IXb1xmn8YD2uMXRHqnyz7whafXjByC5Z
            StCqvKSDVidDmu2bCcbrapCn85VYds09XfbcjFb5g/fC/dnnP9cg3WdQXtXUcXdD
            0hRO1H+F6u2ta83nX5k95SZ1F7N092CHjUkaeFu/X0sHrNtqnYeAHli6+TmzXInS
            XgFUKfCUbvahguzAGTzRNYMuuV3psoBVSZ0Owxeu7qaia7PrzUxYYYAHAZwb8zV6
            VzPfsrUl3poGNiXs2hoefLgI03TodVAGkntewxZKDTT+JxG/OPQBqAfbK3ZevHI=
            =NHkr
            -----END PGP MESSAGE-----
          fp: 528CFD6EA653B5EC59B701F483219063F9FC4626
        - created_at: "2026-01-16T15:46:00Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA81p//ryl184AQ/+OgJBT2a0Q4EQIEgNJtlv/PJ06jANK8OpOerOqizzDbFJ
            cPAuwEA+4uMKrnof3cqzi3InsHTKigy/wY0WAjkSVW5iMjfqWClmUQNrS2Zn87SV
            9h9n81xCVmx7aLsUTbY0HQh3DZi5HOUtaHW2uiG57wqcJrOB1ok88FNCXFL32VJm
            I8AouOdF6sBtmN28hYgbZF7ppKCj8lExngwS7hFijgq5r0dP5dXYgLTsD5INL4Xj
            A+CL1pOxChLX4Bw13MbLqbgk2QWcHEyKH/nl/jKb2TVpWPyi8x5KrDVarwtsN4bt
            f2JFoshmJMHGDr9DX0yL+buF4ph88VK+E2EU2W9r9w/GwP7O/+wiPd3nVDI+iyfY
            Q6HWwJuUL1MO5bBeuoZudyF41JeMchmIYsGCr1OtHljKv3+oNUMnyZOUcIhXekcY
            rFwyXp+xPa4F504idgS5+1wExbuUpIRrvVO0pYv3tyKCpzEt7BCQD6QbW88PudA5
            0aHcy8CO0Nf15tjPJcU47tDWWUyxMWFYpd0mi0OsPLy4d8ujDxnA66TRVJ+xFMsF
            smteklxgypFXfVyOLMSJ6Yg0BX5k+CD1dQDqD1oAzMeiYxXTkSudvuwJoHLRCTUz
            Icy34fxwo9eLeAUJuKHMxQ5720JZ+kKT/D/GhDA318pLLllftiD3CCgJoFjx2urS
            XgG4DZxIdEhKWPIwa312ZY9zSIVc1/aWBIVLDY7flNrZHC1eVcYi5oZMVAkJusUE
            uEG5VuGZoO1OgRZYNuFPejugW06r4wFn9kbueuJY9XcbwRXgim1HKoJs/ZV0aiM=
            =tMVr
            -----END PGP MESSAGE-----
          fp: EE213327AA06F51445BE63B5B4324BD440FD54E3
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
