apiVersion: v1
kind: Secret
metadata:
    name: tailscale-oauth
    namespace: tailscale
type: Opaque
stringData:
    client_id: ENC[AES256_GCM,data:Ie50J70cpkiNXQUBe0tTrLc=,iv:z50fl7aYPZTV1IUQ3EexrCamAlSk51K8w7M/2J+JdEM=,tag:KugAuRr/n34etzWKxBbQEw==,type:str]
    client_secret: ENC[AES256_GCM,data:r3UXOgknBBzQmbNy1oYGgABzwjM4TTRlP0NcxGJ8Za0jqU64oHvbOt+9e9FXEQAhCxi2InPd7H2jXu/Q7Q==,iv:BLhtIUqJ+PCOFfZ04ECchoJv3d1wlnWyWJniaPqB0Ro=,tag:AJPCFh7a55EV1tztJwWWKQ==,type:str]
sops:
    age:
        - recipient: age19lq4dtrxd5qdwkr63gpy2qfwnttu3nxlrp9rxmu659nkt4d8ld7skwj6x9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5NlNMajBTNlZDa0RuWU9X
            VUlodjNtT2tHTVZNZHU5cHNBWE5CcWd4UDM4CkZ1SFJQTmhzVlBSbUJDVk5PRjBP
            OG5yOHhkcGZVZ1VRNFZpT0JkSWdwRTgKLS0tIHo1Vko5bXA4ajBrUUdjaHk2NGZC
            S1pET2dVem54TDNCdllkWjMxRDBWMGMKIGfJlx+fLaW+1CcnUMzkYn4mHRFMYVW+
            V/vl0ajKOshd+iWobI4MZMmu0FUJ8OMeDUwfaJubA6Tan9vuV0elmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-16T16:24:46Z"
    mac: ENC[AES256_GCM,data:DO5gB+nO//BKk4Vs38q5YilCfAk8tcTY1VNOYGwwEher+d3bdd7w+yx/iSpuu060nX/aAWwdX/2rOltMlHzyBkV6/biniZ7t0g2RAm3wsW/NhWbHidmjl93dt5y68ubjqFWimzTb+Dj6fvV0j2JaB6H8FVz/6OvWUBDBPvgj7+I=,iv:9WlySYzuv5zqjbGSbSFrbpWBnDHmNf5FI/abXrT5IqY=,tag:vWNvb6Scfmr4xFAD34U1kg==,type:str]
    pgp:
        - created_at: "2026-01-16T16:24:14Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxdOhYsagpprAQ//YJOFjEeh72cY13nT8PATALDDb715OW4wlZ8eMUPtUzZy
            lluq1N5TIYch3avNGSJDZ8Oj+87fud44PwRN1bX6pltAN0+V7afAyZovXKgyYu6y
            qjbvauH0VuN5D3uBtGgpZSI4r7CRbAI1IwlUEXffQtkqiqJSNF4znhLj0MCvvevn
            hz+vkr4iXF4KRONoySyIU1Vl0639kAE0J3P6T8VbD+3A/x7F4SsrRurAqI2jTORV
            KwZ75OW7p8zyr61BLN9bgILynXmu6aDjkdHJuThE5qc3ZvtofIEKtnUvtQ1PLGsT
            iebOIR3T/PhhfQxkekdq64cxOQ4462S3ibRn42eFemIB/zLCBNqhu5h/7A45S4bP
            XfKh89EcnqQKY2MQ+VZgI7JmTfPmZFj3KX8GGIndSlBeP/oU3hIJXbLe1j5VzCz/
            vsiYO7I/LaTS/7/mNi9AXYA+pfnzyB/r9MPuuJr8KhwqrjXvYjvdSZvsDlgVey9P
            BuuUe2nUUt2C2pzR/JnvRaEt3ZusPHNKYKAUksSFabQWFTbLczHgM6MEdrhobHaL
            gLL14QcGVHvW9hKrwV8eJLh8Mrc+5+LWNwjxr0udg+q5mpXR483Rxz/tCCnpwbUf
            DCYpMdhR1pUu7srurYV5PMUnAssBThAigtsoCe3IeeBCxkzGcJJ29Acj0w2+3PfS
            XgG5Y4fW0e2KJjdfDBO0tvX4e+k0YkLNDonZhta6BqMNdL+DStj2Tynp08Pxh2e5
            MrX1b+yeMhHU0Y+lWIaedEhpxx09Ij4PQvs/aVXGZRwUwfI0CA608q9fetYEzmQ=
            =iILk
            -----END PGP MESSAGE-----
          fp: 528CFD6EA653B5EC59B701F483219063F9FC4626
        - created_at: "2026-01-16T16:24:14Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA81p//ryl184AQ//Tjqv3yra/uscUd5kZPUIj3Wzs48gm5s/eG1+Ks2kUX0V
            VtunyaT139UgXsluJx8GB5+RraQOdYxSIfqMqUtoPPDz6koJ/OS+SOAg8QezRPIN
            GMdC7RdATks4G9OxfWB9vny+Hp5VcASauLQfrIoY6ArOhlPReOOQ1FDvJL7g+E+/
            FxmHVDe+n/VnS9aE5nZJ0JpRYQVKU/R2ZziVGVTnqEsNCLLjoZsycZ0s18E6rNW+
            IC5fQ7M1s1FmtVqX9mfxHgr8RCPPKh4adoT4/a0u2MmaPSiuFrajBkQ+dJ+dpqdd
            V5d+5djb59KW+3SyiYiEQyiSLxmhoI72Q3UMR67XZxlbYKYHgSMVUK0hORN7vY6L
            Nyvzb9RbDyNjhwTh/xqaFom0s+va+x0zorcZ28wGh2465nEsdjWweMcErUR4481b
            Q8edP1U6Cd2sw507zSE1KVpUcl6diyyxRce7M5F+CFHexDoiVkokUAqFARrrLV0x
            m/KDTGuAE50/09wI6PprntsDcyftZZ7x24j2hNOd5PXI+V5PsFVUKKZj6zIahLEr
            hwq+kCAineWaO6l2Lb7/hrJatuPv0bCRwm/WHN2LUBjwtmx/CEqYtZpriI0oNcjn
            9E3MMrDtOWZvY8PwSWCSpjcFyv0qxp9to7W9A+OroIy2nDVywr3FagcGzhhPZvPS
            XgF9SP6uOxHBA8Z9wsyG1AJt+uDPcEJs8JBw30SMmPMPfsydKcgz1cy8UOnI3khe
            kgR0iScVRjnMZrxcUlguK6GA9MVzjsidpKKeiiFscSzTQveMck0xElnuUzts+VE=
            =I8tA
            -----END PGP MESSAGE-----
          fp: EE213327AA06F51445BE63B5B4324BD440FD54E3
    unencrypted_regex: ^(apiVersion|metadata|kind|type|namespace|name)$
    version: 3.11.0
