apiVersion: v1
kind: Secret
metadata:
    name: tailscale-oauth
    namespace: tailscale
type: Opaque
stringData:
    client_id: REPLACE_WITH_YOUR_OAUTH_CLIENT_ID
    client_secret: REPLACE_WITH_YOUR_OAUTH_CLIENT_SECRET
