# Note: Tailscale operator v1.92.5 has limitations with TCP LoadBalancer services
# The serve configuration must be manually applied after pod creation:
#   kubectl exec -n tailscale <proxy-pod> -- tailscale serve --bg --tcp 22 tcp://<clusterip>:22
#
# This configuration persists as long as the proxy pod is running.
# For automatic configuration across restarts, this would need operator support
# or a custom init container/job.
apiVersion: v1
kind: Service
metadata:
  name: forgejo-ssh-tailscale
  namespace: forgejo
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "forgejo-ssh"
    tailscale.com/tags: "tag:k8s"
spec:
  type: ClusterIP
  ports:
    - name: ssh
      port: 22
      targetPort: 2222
      protocol: TCP
  selector:
    app.kubernetes.io/name: forgejo
