apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: forgejo-postgres-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./forgejo-postgres-secret.yaml
